version: '2'
services:
  zookeeper:
    image: jplock/zookeeper:latest
    network_mode: 'host'

  mesos_master:
    image: lxsameer/mesos:latest
    environment:
      MESOS_ZK: "zk://127.0.0.1:2181/mesos"
      MESOS_QUORUM: "1"
      # For production use relpicated_log
      MESSOS_REGISTRY: 'in_memory'
      MESOS_IP: '0.0.0.0'
      MESOS_WORK_DIR: '/var/lib/mesos'
      MESOS_LOG_DIR: '/var/log/mesos'

    network_mode: 'host'
    depends_on:
      - zookeeper

  mesos_slave:
    image: lxsameer/mesos:latest
    depends_on:
      - mesos_master

    network_mode: 'host'
    environment:
      MESOS_HOSTNAME: 'slave_1'
      MESOS_MASTER: 'zk://127.0.0.1:2181/mesos'
      MESOS_LOG_DIR: '/var/log/mesos'
      MESOS_LOGGING_LEVEL: 'INFO'
      MESOS_WORK_DIR: '/var/lib/mesos'
      MESOS_SWITCH_USER: '0'
      MESOS_CONTAINERIZERS: 'docker,mesos'
      MESOS_SLAVE: 'true'
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/sys:/sys"
      - "/cgroup:/cgroup"
